# permissions for end users to edit boutiqueshops.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: boutiqueshop-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: boutique-shop-operator
    app.kubernetes.io/part-of: boutique-shop-operator
    app.kubernetes.io/managed-by: kustomize
  name: boutiqueshop-editor-role
rules:
- apiGroups:
  - demo.openshift.com
  resources:
  - boutiqueshops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.openshift.com
  resources:
  - boutiqueshops/status
  verbs:
  - get
